import { NextRequest, NextResponse } from 'next/server'

interface MusicInfoRequest {
  artist: string
  title: string
  language?: string
}

// Configuração da API do Gemini
const API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent"
const API_KEY = process.env.GEMINI_API_KEY

export async function POST(request: NextRequest) {
  try {
    const { artist, title, language = 'pt-BR' }: MusicInfoRequest = await request.json()

    if (!artist || !title) {
      return NextResponse.json(
        { error: 'Artist and title are required' },
        { status: 400 }
      )
    }

    console.log(`🎵 DJ Orky pesquisando informações sobre: ${artist} - ${title}`)

    // Prompt para o Gemini em português
    const prompt = `
Você é o DJ Orky, um DJ especialista em música retrô da Rádio Tatuapé FM. 
Preciso que você analise a música "${title}" do(a) artista "${artist}" e forneça informações interessantes e curiosas.

Por favor, responda em formato JSON com as seguintes informações:

1. curiosities: Curiosidades interessantes sobre a música (2-3 frases curtas e envolventes)
2. bandInfo: Informações sobre a banda/artista (2-3 frases sobre história, estilo, importância)  
3. members: Informações sobre os integrantes principais, vocalistas ou formação (1-2 frases)
4. era: A época/década da música (ex: "Anos 80", "Final dos 90", "Início dos 2000")
5. genre: Gênero musical principal (ex: "Pop Rock", "New Wave", "Grunge")
6. funFact: Um fato curioso, interessante ou divertido sobre a música ou banda (1 frase impactante)

IMPORTANTE:
- Mantenha as informações precisas e interessantes
- Use linguagem brasileira e descontraída
- Seja específico sobre curiosidades reais da música/banda
- Se não souber detalhes específicos, foque no que é conhecido sobre o artista
- Responda APENAS o JSON, sem texto adicional

Exemplo:
{
  "curiosities": "Esta música foi gravada em apenas uma tomada e se tornou um dos maiores sucessos da década.",
  "bandInfo": "A banda revolucionou o cenário musical com seu som único e letras marcantes.",
  "members": "Formada por talentosos músicos que se conheceram na escola.",
  "era": "Anos 90",
  "genre": "Pop Rock",
  "funFact": "O videoclipe foi gravado com orçamento de apenas 50 dólares!"
}
`

    // Chamar a API do Gemini
    const geminiResponse = await fetch(`${API_URL}?key=${API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt
              }
            ]
          }
        ],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 1024,
        },
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_HATE_SPEECH",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          }
        ]
      })
    })

    if (!geminiResponse.ok) {
      const errorData = await geminiResponse.text()
      console.error('❌ Erro na API do Gemini:', geminiResponse.status, errorData)
      throw new Error(`Gemini API error: ${geminiResponse.status}`)
    }

    const geminiData = await geminiResponse.json()
    console.log('📤 Resposta do Gemini recebida')
    
    // Extrair o texto da resposta do Gemini
    const generatedText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text
    
    if (!generatedText) {
      throw new Error('No content generated by Gemini')
    }

    console.log('📝 Texto gerado pelo Gemini:', generatedText.substring(0, 200) + '...')

    // Tentar fazer parse do JSON gerado
    let musicInfo
    try {
      // Limpar o texto e tentar extrair o JSON
      let jsonText = generatedText.trim()
      
      // Remover possíveis marcadores de código se existirem
      jsonText = jsonText.replace(/```json\s*/g, '').replace(/```\s*/g, '')
      
      // Tentar encontrar o JSON na resposta
      const jsonMatch = jsonText.match(/\{[\s\S]*\}/)
      if (jsonMatch) {
        jsonText = jsonMatch[0]
      }
      
      musicInfo = JSON.parse(jsonText)
      console.log('✅ JSON parsed com sucesso')
    } catch (parseError) {
      console.error('❌ Erro ao fazer parse do JSON do Gemini:', parseError)
      console.log('🔍 Texto completo gerado:', generatedText)
      
      // Fallback se o JSON estiver malformado
      musicInfo = {
        curiosities: `"${title}" é uma música icônica de ${artist} que marcou uma geração com sua sonoridade única.`,
        bandInfo: `${artist} é reconhecido(a) mundialmente por sua contribuição única para a música e por sucessos atemporais.`,
        members: `A formação de ${artist} conta com talentosos músicos que criaram um som inconfundível.`,
        era: 'Clássico Atemporal',
        genre: 'Pop/Rock',
        funFact: `"${title}" continua sendo uma das músicas mais pedidas pelos ouvintes das rádios!`
      }
    }

    // Garantir que temos todos os campos necessários
    musicInfo.artist = artist
    musicInfo.title = title
    musicInfo.recommendation = `Continue ouvindo a Rádio Tatuapé FM para descobrir mais sucessos como "${title}"!`

    console.log('✅ Informações processadas para:', `${artist} - ${title}`)

    return NextResponse.json({
      success: true,
      musicInfo,
      source: 'gemini',
      timestamp: new Date().toISOString()
    })

  } catch (error: any) {
    console.error('❌ Erro na API do DJ Orky Music Info:', error)
    
    // Em caso de erro, retornar informações básicas mas interessantes
    let fallbackData
    try {
      fallbackData = await request.json()
    } catch {
      fallbackData = { artist: 'Artista Desconhecido', title: 'Música' }
    }
    
    const { artist = 'Artista', title = 'Música' } = fallbackData

    return NextResponse.json({
      success: true, // Ainda retornamos sucesso para não quebrar a interface
      musicInfo: {
        artist,
        title,
        curiosities: `"${title}" é uma música especial que faz parte da trilha sonora de muitas memórias. ${artist} conquistou fãs com essa obra marcante!`,
        bandInfo: `${artist} é um(a) artista que deixou sua marca na história da música, criando sucessos que atravessam gerações.`,
        members: `A formação musical por trás de "${title}" demonstra o talento e a paixão pela música que define ${artist}.`,
        era: 'Era Dourada',
        genre: 'Clássico',
        funFact: `Toda vez que "${title}" toca na rádio, é impossível não cantar junto!`,
        recommendation: `Continue ligado na Rádio Tatuapé FM para mais sucessos atemporais como este!`
      },
      source: 'error_fallback',
      error: error.message,
      timestamp: new Date().toISOString()
    })
  }
}

// Endpoint GET para testar a API
export async function GET(request: NextRequest) {
  return NextResponse.json({
    message: 'DJ Orky Music Info API',
    status: 'online',
    usage: 'POST com { artist: "Nome do Artista", title: "Nome da Música" }',
    timestamp: new Date().toISOString()
  })
}
